-- MySQL Script generated by MySQL Workbench
-- Wed Jul  7 18:59:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alkemyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alkemyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alkemyDB` DEFAULT CHARACTER SET utf8 ;
USE `alkemyDB` ;

-- -----------------------------------------------------
-- Table `alkemyDB`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemyDB`.`operations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `concept` VARCHAR(500),
  `amount` INT(11),
  `type` VARCHAR(45),
  `date` DATE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
